import type { ProviderCapabilityCard, ProviderId } from "../core/providers.ts";
import { assertProviderCapabilityCard } from "../core/providers.ts";

const yes = true;
const no = false;
const documented = "documented_unverified";
const unsupported = "unsupported";

export const PROVIDERS: readonly ProviderCapabilityCard[] = [
  {
    id: "mercury",
    displayName: "Mercury",
    role: "institution",
    capabilities: {
      accounts: yes,
      attachments: yes,
      balances: yes,
      categories: yes,
      credit: yes,
      customers: yes,
      events: yes,
      invoices: yes,
      transactions: yes,
      counterparties: yes,
      oauth: yes,
      onboarding: yes,
      organization: yes,
      payments: yes,
      paymentDrafts: yes,
      internalTransfers: yes,
      safes: yes,
      statements: yes,
      treasury: yes,
      users: yes,
      cards: yes,
      webhooks: yes,
      sandbox: yes,
      cardSandbox: yes,
      requiresTpp: no,
      requiresBusinessAccount: yes,
      sensitiveCardData: no,
    },
    scopes: {
      read: ["accounts:read", "transactions:read"],
      payments: ["transactions:write", "RequestSendMoney"],
      cards: ["cards:write"],
      sensitiveCardData: [],
    },
    cardOperations: {
      createVirtual: documented,
      updateSettings: documented,
      freeze: documented,
      unfreeze: documented,
      terminate: documented,
      revealSensitiveData: unsupported,
      productionOnly: no,
    },
    environments: ["sandbox", "production"],
    docs: [
      "https://docs.mercury.com/llms.txt",
      "https://docs.mercury.com/changelog",
      "https://docs.mercury.com/reference/listcards",
      "https://docs.mercury.com/reference/listtransactions",
      "https://docs.mercury.com/reference/getaccountcards",
      "https://docs.mercury.com/reference/createtransaction",
      "https://docs.mercury.com/docs/supported-tools-on-mercury-mcp",
    ],
    releaseGate: "Verify Mercury full-surface token scopes, IP policy, sandbox behavior, payload schemas, webhooks, AR/file redaction, OAuth, and virtual-card lifecycle.",
    limitations: [
      "Only accounts, balances, organization-wide cards, and organization-wide transactions have live-read adapters today; the rest of the current API surface is descriptor/conformance-plan only.",
      "Card and money movement APIs remain non-executable until conformance verifies sandbox/live behavior and approval/idempotency/audit gates.",
      "Sensitive card data is unsupported until an exact official sensitive-card endpoint source is documented.",
    ],
  },
  {
    id: "bunq",
    displayName: "bunq",
    role: "institution",
    capabilities: {
      accounts: yes,
      attachments: no,
      balances: yes,
      categories: no,
      credit: no,
      customers: no,
      events: no,
      invoices: no,
      transactions: yes,
      counterparties: yes,
      oauth: no,
      onboarding: no,
      organization: no,
      payments: yes,
      paymentDrafts: yes,
      internalTransfers: yes,
      safes: no,
      statements: no,
      treasury: no,
      users: no,
      cards: yes,
      webhooks: yes,
      sandbox: yes,
      cardSandbox: yes,
      requiresTpp: no,
      requiresBusinessAccount: yes,
      sensitiveCardData: no,
    },
    scopes: {
      read: ["monetary-account:read", "payment:read"],
      payments: ["payment:write"],
      cards: ["card:write"],
      sensitiveCardData: [],
    },
    cardOperations: {
      createVirtual: documented,
      updateSettings: documented,
      freeze: documented,
      unfreeze: documented,
      terminate: unsupported,
      revealSensitiveData: unsupported,
      productionOnly: no,
    },
    environments: ["sandbox", "production"],
    docs: [
      "https://doc.bunq.com/",
      "https://doc.bunq.com/basics/bunq-api-objects/payment",
      "https://doc.bunq.com/tutorials/how-to-manage-your-cards/ordering-a-card",
    ],
    releaseGate: "Implement and verify API context, device/session persistence, X-Bunq headers, signing/OAuth, sandbox, drafts, and cards.",
    limitations: [
      "Official SDKs are not the preferred current integration path; build direct API contracts and signing tests.",
      "Sensitive card/CVC data is unsupported until an exact official endpoint source is documented.",
    ],
  },
  {
    id: "revolut-business",
    displayName: "Revolut Business",
    role: "institution",
    capabilities: {
      accounts: yes,
      attachments: no,
      balances: yes,
      categories: no,
      credit: no,
      customers: no,
      events: no,
      invoices: no,
      transactions: yes,
      counterparties: yes,
      oauth: no,
      onboarding: no,
      organization: no,
      payments: yes,
      paymentDrafts: yes,
      internalTransfers: yes,
      safes: no,
      statements: no,
      treasury: no,
      users: no,
      cards: yes,
      webhooks: yes,
      sandbox: yes,
      cardSandbox: no,
      requiresTpp: no,
      requiresBusinessAccount: yes,
      sensitiveCardData: yes,
    },
    scopes: {
      read: ["READ"],
      payments: ["PAY"],
      cards: ["WRITE"],
      sensitiveCardData: ["READ_SENSITIVE_CARD_DATA"],
    },
    cardOperations: {
      createVirtual: documented,
      updateSettings: documented,
      freeze: documented,
      unfreeze: documented,
      terminate: documented,
      revealSensitiveData: documented,
      productionOnly: yes,
    },
    environments: ["sandbox", "production"],
    docs: [
      "https://developer.revolut.com/docs/business/business-api",
      "https://developer.revolut.com/docs/guides/manage-accounts/cards/manage-cards",
      "https://developer.revolut.com/docs/business/create-card",
    ],
    releaseGate: "Verify Business API scopes, JWT/certificate auth, IP controls, and production-only card management.",
    limitations: ["Business API card management is documented as unavailable in Sandbox; tests must not claim sandbox card execution."],
  },
  {
    id: "erste-bcr",
    displayName: "Erste BCR",
    role: "open_banking_access",
    capabilities: {
      accounts: yes,
      attachments: no,
      balances: yes,
      categories: no,
      credit: no,
      customers: no,
      events: no,
      invoices: no,
      transactions: yes,
      counterparties: no,
      oauth: no,
      onboarding: no,
      organization: no,
      payments: yes,
      paymentDrafts: no,
      internalTransfers: no,
      safes: no,
      statements: no,
      treasury: no,
      users: no,
      cards: no,
      webhooks: no,
      sandbox: yes,
      cardSandbox: no,
      requiresTpp: yes,
      requiresBusinessAccount: no,
      sensitiveCardData: no,
    },
    scopes: {
      read: ["AIS"],
      payments: ["PIS"],
      cards: [],
      sensitiveCardData: [],
    },
    cardOperations: {
      createVirtual: unsupported,
      updateSettings: unsupported,
      freeze: unsupported,
      unfreeze: unsupported,
      terminate: unsupported,
      revealSensitiveData: unsupported,
      productionOnly: no,
    },
    environments: ["sandbox", "production"],
    docs: [
      "https://www.bcr.ro/en/open-banking",
      "https://developers.erstegroup.com/",
      "https://www.erstegroup.com/en/erste-open-banking",
    ],
    releaseGate: "Treat as PSD2 AIS/PIS only until a commercial API grants broader account or card control.",
    limitations: ["Requires PSD2/TPP consent and SCA flows; no direct card-control capability is exposed in the public scope."],
  },
] as const;

for (const provider of PROVIDERS) {
  assertProviderCapabilityCard(provider);
}

export function listProviders(): readonly ProviderCapabilityCard[] {
  return PROVIDERS;
}

export function getProvider(id: ProviderId): ProviderCapabilityCard | undefined {
  return PROVIDERS.find((provider) => provider.id === id);
}
